### ISSUE TITLE
Errors when execution in win 10 python 3.7

### ISSUE THREAD

**Issue by jayateertha043** [s0md3v/XSStrike#136]
**Describe the bug**
PLease fix this isssue don't understand why i get these many errors

**To Reproduce**
python xsstrike.py -u "http://www.dubjazzsalsa.com/index.php?mod=shop&redirsearch=1&task=fastSearch&fastSearch=hi"
happens with all websites
**Screenshots**
C:\XSStrike-master>python xsstrike.py -u "http://www.dubjazzsalsa.com/index.php?mod=shop&redirsearch=1&task=fastSearch&fastSearch=hi"

        XSStrike v3.0.4

Traceback (most recent call last):
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 360, in _error_catcher
    yield
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 666, in read_chunked
    self._update_chunk_length()
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 598, in _update_chunk_length
    line = self._fp.fp.readline()
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 694, in read_chunked
    self._original_response.close()
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='www.dubjazzsalsa.com', port=80): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xsstrike.py", line 330, in <module>
    singleTarget(target, paramData, verbose, encoding)
  File "xsstrike.py", line 140, in singleTarget
    response = requester(target, {}, headers, GET, delay, timeout).text
  File "C:\XSStrike-master\core\requester.py", line 22, in requester
    timeout=timeout, verify=False, proxies=core.config.proxies)
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 686, in send
    r.content
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\GURU\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 757, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.dubjazzsalsa.com', port=80): Read timed out.

**Environment:**
 - OS: win 10
 -firefox latest version
 - Python version 3.7

**Some Questions**

- [x ] I am using the latest version of XSStrike.
- [x] I installed the dependecies using `pip3` instead of `pip`
- [x ] I have read the documentation before submitting this issue.
- [ x] I have checked the other issues to see if someone reported this before.

**Comment by s0md3v** [comment]
Looks like you have a really slow network connection.
Try changing the value of timeout in `/core/config.py` to somewhere between `20` and `30`.

**Comment by s0md3v** [comment]
Well it's definitely not a fault of XSStrike.
There is something wrong with your configuration.

Try doing this in your python interpreter

```
~> python3
Python 3.6.7 (default, Oct 21 2018, 08:08:16) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://github.com')
<Response [200]>
>>> 
```

**Comment by jayateertha043** [comment]
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit
(AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> >>> requests.get('https://github.com')
  File "<stdin>", line 1
    >>> requests.get('https://github.com')
     ^
SyntaxError: invalid syntax
>>> <Response [200]>
  File "<stdin>", line 1
    <Response [200]>
    ^
SyntaxError: invalid syntax
>>>

**Comment by jayateertha043** [comment]
kindly help me solve this issue
