### ISSUE TITLE
TypeError: browserEngine() missing 1 required positional argument: 'response'

### ISSUE THREAD

**Issue by coIev** [s0md3v/XSStrike#153]
**Describe the bug**
The recent update of XSStrike throws a a TypeError.

**To Reproduce**
python3 xsstrike.py -u http://brutelogic.com.br/xss.php?b1=1

        XSStrike v3.1.0

[~] Checking for DOM vulnerabilities
[+] WAF Status: Offline
[!] Testing parameter: b1
[!] Reflections found: 1
[~] Analysing reflections
[~] Generating payloads
[!] Payloads generated: 3092
Traceback (most recent call last):
  File "xsstrike.py", line 130, in <module>
    scan(target, paramData, verbose, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/root/XSStrike/modes/scan.py", line 127, in scan
    success = browserEngine(response)
TypeError: browserEngine() missing 1 required positional argument: 'response'

- [x] I am using the latest version of XSStrike.
- [x] I installed the dependecies using `pip3` instead of `pip`
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?

**Comment by coIev** [comment]
Not sure how the bug issue got messed up like this 😖 - but here's the screenshot:

![download](https://user-images.githubusercontent.com/44411392/48849223-c273ab00-ed5a-11e8-8af5-ff8096552e56.png)
