### ISSUE TITLE
Syntax error??

### ISSUE THREAD

**Issue by aesthetick** [s0md3v/XSStrike#155]
Hey, i got this error when i try to execute the python script, and i dont know why.
Can you help me with this?

root@parrot:~/XSStrike# python xsstrike.py 
Traceback (most recent call last):
  File "xsstrike.py", line 13, in <module>
    from core.photon import photon
  File "/root/XSStrike/core/photon.py", line 27
    print ('%s Parsing %s' % (run, printableTarget), end='\r')
                                                        ^
SyntaxError: invalid syntax

I tried using python 3 and more but i get similar errors. :((

**Comment by aesthetick** [comment]
well i havent, but all my requirements are satisfied.
but thanks ill try that.
