### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jplopezy** [s0md3v/XSStrike#156]
i have this error

root@localhost:~/XSStrike#  python3 xsstrike.py -u https://test.myshopify.com/search?q=aaaaaaaaa

        XSStrike v3.1.1

[~] Checking for DOM vulnerabilities
[+] Potentially vulnerable objects found
------------------------------------------------------------
185 var originalDocumentWrite = document.write;
186 document.write = customDocumentWrite;
188 document.write = originalDocumentWrite;
241 
298 
------------------------------------------------------------
[+] WAF Status: Offline
[!] Testing parameter: q
[!] Reflections found: 6
[~] Analysing reflections
[~] Generating payloads
[!] Payloads generated: 10
Traceback (most recent call last):
  File "xsstrike.py", line 144, in <module>
    scan(target, paramData, verbose, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/root/XSStrike/modes/scan.py", line 130, in scan
    success = browserEngine(response)
  File "/root/XSStrike/core/browserEngine.py", line 13, in browserEngine
    browser = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by s0md3v** [comment]
Please use a recent version of firefox.
