### ISSUE TITLE
Help needed 

### ISSUE THREAD

**Issue by rafi2312** [s0md3v/XSStrike#164]
rafi@Kaali2018:~/XSStrike$ python3 xsstrike.py

	XSStrike v3.1.1

Traceback (most recent call last):
  File "xsstrike.py", line 32, in <module>
    from modes.crawl import crawl
  File "/home/rafi/XSStrike/modes/crawl.py", line 7, in <module>
    from core.filterChecker import filterChecker
  File "/home/rafi/XSStrike/core/filterChecker.py", line 1, in <module>
    from core.checker import checker
  File "/home/rafi/XSStrike/core/checker.py", line 2, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'

I'm getting this issue when i start for first command after installing
Here I'm using Kali 2018.4 Version

**Comment by coIev** [comment]
pip3 install fuzzywuzzy

**Comment by rafi2312** [comment]
I already tried these commands, even after using these commands i'm getting same error...
Is that because of Kali 2018.4 ????

**Comment by s0md3v** [comment]
Not an issue with XSStrike.
