### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by nice9uy** [s0md3v/XSStrike#179]
Hi..
I have a problem with selenium.common.exceptions.SessionNotCreatedException.
Can you tell me , how to fix it?

this is a log file

Traceback (most recent call last):
  File "xsstrike.py", line 146, in <module>
    scan(target, paramData, verbose, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/home/nice9uy/Documents/Hacking/XSStrike/modes/scan.py", line 130, in scan
    success = browserEngine(response)
  File "/home/nice9uy/Documents/Hacking/XSStrike/core/browserEngine.py", line 13, in browserEngine
    browser = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilit

Thanks.

**Comment by s0md3v** [comment]
Install latest `firefox` and `geckodriver`.
