### ISSUE TITLE
dependencies error

### ISSUE THREAD

**Issue by evantoday** [s0md3v/XSStrike#180]
im using pip3 and python3

        XSStrike v3.1.2

Traceback (most recent call last):
  File "xsstrike.py", line 34, in <module>
    from core.photon import photon
  File "/home/ubuntu/workspace/hack/XSStrike/core/photon.py", line 7, in <module>
    from core.requester import requester
  File "/home/ubuntu/workspace/hack/XSStrike/core/requester.py", line 4, in <module>
    from urllib3.exceptions import ProtocolError
ImportError: cannot import name 'ProtocolError

**Comment by s0md3v** [comment]
Update `requests` library
