### ISSUE TITLE
[error] Can not connect to the Service geckodriver

### ISSUE THREAD

**Issue by ghost** [s0md3v/XSStrike#184]
i keep running this issue 

[!] Payloads generated: 70623
Traceback (most recent call last):
  File "xsstrike.py", line 146, in <module>
    scan(target, paramData, verbose, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/root/XSStrike/modes/scan.py", line 130, in scan
    success = browserEngine(response)
  File "/root/XSStrike/core/browserEngine.py", line 13, in browserEngine
    browser = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver

**Comment by s0md3v** [comment]
You need to install `geckodriver`

**Comment by soupnatzi** [comment]
i have geckodriver setup.

**Comment by s0md3v** [comment]
Looks like you did not setup it properly.
Don't worry, just run this command as root and everything will work:
```bash
wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz && mkdir geckodriver && tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver && export PATH=$PATH:$PWD/geckodriver
```

**Comment by soupnatzi** [comment]
it's still not working it seems it's an issue with Firefox61 after doing some research.
