### ISSUE TITLE
Hello somdev i m getting this error please fix it

### ISSUE THREAD

**Issue by gamersushil** [s0md3v/XSStrike#199]
XSStrike v3.1.2

Traceback (most recent call last):
  File "xsstrike.py", line 122, in <module>
    from modes.scan import scan
  File "/home/sushil/XSStrike/modes/scan.py", line 6, in <module>
    from core.browserEngine import browserEngine
  File "/home/sushil/XSStrike/core/browserEngine.py", line 6, in <module>
    from selenium import webdriver
ImportError: No module named 'selenium'
sushil@sushil-Aspire-ES1-572:~/XSStrike$

**Comment by s0md3v** [comment]
install selenium and next time google the error before asking other people.
