### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by oldesec** [s0md3v/XSStrike#215]
Hi.

I can often see the following errors.

Thanks.

```
Traceback (most recent call last):
  File "xsstrike.py", line 167, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/root/XSStrike/modes/scan.py", line 62, in scan
    params = getParams(target, paramData, GET)
  File "/root/XSStrike/core/utils.py", line 181, in getParams
    params[each[0]] = each[1]
TypeError: 'NoneType' object does not support item assignment
```

**Comment by iqzer0** [comment]
[~] Checking for DOM vulnerabilities 
Traceback (most recent call last):
  File "xsstrike.py", line 167, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/home/iqzer0/tools/XSStrike/modes/scan.py", line 62, in scan
    params = getParams(target, paramData, GET)
  File "/home/iqzer0/tools/XSStrike/core/utils.py", line 181, in getParams
    params[each[0]] = each[1]
TypeError: 'NoneType' object does not support item assignment

**Comment by iqzer0** [comment]
i got the same issue too

**Comment by s0md3v** [comment]
Would it be possible for you to provide a webpage where this error occurs?

You can dm on [twitter](https://twitter.com/s0md3v) or email me at s0md3v@gmail.com

**Comment by s0md3v** [comment]
@iqzer0 & @oldesec any updates?

**Comment by MushR00m** [comment]
i got the same issue, 

```Traceback (most recent call last):
  File "xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/XSStrike/modes/scan.py", line 48, in scan
    params = getParams(target, paramData, GET)
  File "/XSStrike/core/utils.py", line 181, in getParams
    params[each[0]] = each[1]
TypeError: 'NoneType' object does not support item assignment
```

error url like `http://test.example.com/xx/xx.php?&a=value&c=payload`

maybe `?&`??? , when i delete `&`, url like `xx.php?a=value`

xsstrike run ok ^^

**Comment by kkshitish** [comment]
Hello Guys, 

Can u tell me how may I reproduce this issue. It will help me to patch this issue.
