### ISSUE TITLE
how to fix this selenium error ?

### ISSUE THREAD

**Issue by mukhlisakbr** [s0md3v/XSStrike#237]
Traceback (most recent call last):
  File "xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/home/cabox/workspace/XSStrike/modes/scan.py", line 37, in scan
    init_browser()
  File "/home/cabox/workspace/XSStrike/core/browserEngine.py", line 17, in init_browser
    browser = webdriver.Firefox(options=options)
  File "/home/cabox/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/cabox/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/cabox/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/cabox/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/cabox/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by KalibRx** [comment]
If you're sure geckodriver is in your $PATH then you likely need to upgrade Firefox to a newer version.

**Comment by Garithe** [comment]
could anyone give a straight solution to this bug?

**Comment by IAmStoxe** [comment]
> could anyone give a straight solution to this bug?

I did if you read my comment above yours.

**Comment by awam07** [comment]
@Garithe you can download geckodriver from here, scroll down and choose the one for your OS, https://github.com/mozilla/geckodriver/releases then copy geckodriver to /usr/local/bin.

**Comment by Garithe** [comment]
> @Garithe you can download geckodriver from here, scroll down and choose the one for your OS, https://github.com/mozilla/geckodriver/releases then copy geckodriver to /usr/local/bin.

just write a simple script to finish my work, but thank you all the same

**Comment by devcoinfet** [comment]
This does not fix the problem

.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver


now this error happens over tor it seems to only conflate the issue

**Comment by s0md3v** [comment]
Are you sure the `geckodriver` is set-up correctly and you have `firefox` and `selenium` installed?
If not, follow the commands below

```bash
wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
mkdir geckodriver
tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
export PATH=$PATH:$PWD/geckodriver
```

**Comment by aphetsansino** [comment]
Termux usage: 
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 1520, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/data/data/com.termux/files/home/XSStrike/modes/scan.py", line 37, in scan
    init_browser()
  File "/data/data/com.termux/files/home/XSStrike/core/browserEngine.py", line 17, in init_browser
    browser = webdriver.Firefox(options=options)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by awesomeaakash** [comment]
This is what i am getting ->

`XSStrike v3.1.4

Traceback (most recent call last):
  File "xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/home/aakash/bounty/tools/XSStrike/modes/scan.py", line 37, in scan
    init_browser()
  File "/home/aakash/bounty/tools/XSStrike/core/browserEngine.py", line 17, in init_browser
    browser = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited proces`

**Comment by s0md3v** [comment]
`selenium` has been removed in the latest, this issue can be closed now.
