### ISSUE TITLE
Install with selenium Error  

### ISSUE THREAD

**Issue by xx-zhang** [s0md3v/XSStrike#246]
**Describe the bug**
```
[root@pentools XSStrike]# ../xss_venv/bin/python xsstrike.py -u http://192.168.2.99:9070/

	XSStrike v3.1.4

Traceback (most recent call last):
  File "xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/home/XSStrike/modes/scan.py", line 37, in scan
    init_browser()
  File "/home/XSStrike/core/browserEngine.py", line 15, in init_browser
    browser = webdriver.Firefox(options=options)
  File "/home/xss_venv/lib64/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/xss_venv/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/xss_venv/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/xss_venv/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/xss_venv/lib64/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

**To Reproduce**
Explain how the issue can be reproduced.

**Screenshots**
If applicable, add screenshots or paste terminal output to help explain your problem.
Feel free to hide sensitive information like the URL of the target.

**Potential cause or fix**
Do you know what could be causing the problem or how to fix it?

**Environment:**
 - OS: [e.g. Kali Rolling 2018.2]
 - Browser [e.g. Firefox Mozilla Firefox 60.6.1]
 - Python version [e.g. 3.6.6]
-  selenium==3.141.0

**Some Questions**

- [*] I am using the latest version of XSStrike.
- [*] I installed the dependecies using `pip3` instead of `pip`
- [ ] I have read the documentation before submitting this issue.
- [*] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?

**Comment by sahruldotid** [comment]
$ sudo apt install xvfb
$ /usr/bin/Xvfb :99 -ac -screen 0 1024x768x8 & export DISPLAY=":99"

**Comment by s0md3v** [comment]
Selenium is no longer required
