### ISSUE TITLE
 Error while running "striker" option

### ISSUE THREAD

**Issue by marcelo321** [s0md3v/XSStrike#247]
there is no problem if i run python3 xsstriker.py -u example.com --fuzzer. but when i try the same command without "--fuzzer" i get this:

root@kali:~/XSStrike# python3 xsstrike.py -u https://sumup.com/blog/?page=12-2
```

	XSStrike v3.1.4

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/root/XSStrike/modes/scan.py", line 37, in scan
    init_browser()
  File "/root/XSStrike/core/browserEngine.py", line 15, in init_browser
    browser = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
```

**Comment by s0md3v** [comment]
@IAmStoxe Did you imperilment browser integration for fuzzer as well?

**Comment by s0md3v** [comment]
`selenium` has been removed, this issue isn't relevant anymore.
