### ISSUE TITLE
Error (on Windows)

### ISSUE THREAD

**Issue by Xprogrammer777** [s0md3v/XSStrike#320]
Hello,
I am experiencing this error when I open XSStrike (in the CMD).

C: \ Users \ my_username \ Desktop \ XSS> xsstrike.py

        XSStrike v3.1.4

Traceback (most recent call last):
  File "C: \ Users \ my_username \ Desktop \ XSS\ xsstrike.py", line 117, in <module>
    from core.photon import photon
  File "C: \ Users \ my_username \ Desktop \ XSS \ core \ photon.py", line 8, in <module>
    from core.requester import requester
  File "C: \ Users \ my_username \ Desktop \ XSS \ core \ requester.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Can you help me?

Xprogramer777

**Comment by s0md3v** [comment]
install `requests` module.

**Comment by utomoaleena** [comment]
hi Mr i have a problem same with you 
![Screenshot_2023-03-18-15-22-16-25_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/115866378/226094298-a40c32be-d888-4eaa-89d2-d41a24c35e64.jpg)

can you help me @s0md3v  🙏🥲
