### ISSUE TITLE
traceback issue

### ISSUE THREAD

**Issue by BenCdesire** [s0md3v/XSStrike#321]
I try to run xsstrike on my owasp broken web app and I get this result all the time:
~] Checking for DOM vulnerabilities 
[+] WAF Status: Offline 
[!] Testing parameter: page 
[!] Reflections found: 6 
[~] Analysing reflections 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.88.132', port=80): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/XSStrike/xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/home/kali/XSStrike/modes/scan.py", line 80, in scan
    efficiencies = filterChecker(
  File "/home/kali/XSStrike/core/filterChecker.py", line 28, in filterChecker
    efficiencies = checker(
  File "/home/kali/XSStrike/core/checker.py", line 15, in checker
    response = requester(url, replaceValue(
  File "/home/kali/XSStrike/core/requester.py", line 37, in requester
    response = requests.get(url, params=data, headers=headers,
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.88.132', port=80): Read timed out. (read timeout=10)

**Comment by s0md3v** [comment]
Fixed.

**Comment by Jaye72** [comment]
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[~] Checking for DOM vulnerabilities 
[!!] Unable to connect to the target. 
Traceback (most recent call last):
  File "/home/darkpheonix/XSStrike/xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "/home/darkpheonix/XSStrike/modes/scan.py", line 52, in scan
    WAF = wafDetector(
          ^^^^^^^^^^^^
  File "/home/darkpheonix/XSStrike/core/wafDetector.py", line 25, in wafDetector
    if int(code) >= 400:
       ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
