### ISSUE TITLE
how can i fix it

### ISSUE THREAD

**Issue by santhosh0000000** [s0md3v/XSStrike#326]
Traceback (most recent call last):
  File "/home/random/XSStrike/xsstrike.py", line 117, in <module>
    from core.photon import photon
  File "/home/random/XSStrike/core/photon.py", line 8, in <module>
    from core.requester import requester
  File "/home/random/XSStrike/core/requester.py", line 2, in <module>
    import requests
  File "/home/random/.local/lib/python3.9/site-packages/requests/__init__.py", line 44, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

**Comment by santhosh0000000** [comment]
how can i fix it

**Comment by normface** [comment]
> ModuleNotFoundError: No module named 'chardet'

pip3 install chardet
