### ISSUE TITLE
Causes this error when running...i am using latest version of xsstrike.

### ISSUE THREAD

**Issue by UxplnJDK** [s0md3v/XSStrike#372]
Traceback (most recent call last):
  File "/home/sunil/python-tools/XSStrike/xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "/home/sunil/python-tools/XSStrike/modes/scan.py", line 81, in scan
    vectors = generator(occurences, response.text)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunil/python-tools/XSStrike/core/generator.py", line 136, in generator
    closer = jsContexter(script)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/sunil/python-tools/XSStrike/core/jsContexter.py", line 11, in jsContexter
    pre = re.sub(r'(?s)\{.*?\}|(?s)\(.*?\)|(?s)".*?"|(?s)\'.*?\'', '', pre)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 12

**Comment by 0x9Fahad** [comment]
exactly same issue here, might be the python3 libraries, testing for a solution right now.

**Comment by notkearash** [comment]
Seems like a proxy issue. Solved when I removed the `--proxy` flag.

**Comment by sriramoffcl** [comment]
.

**Comment by notkearash** [comment]
@0x9Fahad 
```
$ python xsstrike.py -u 'https://example.app/search?search=hi'

	XSStrike v3.1.5

[~] Checking for DOM vulnerabilities 
[-] WAF detected: CloudFlare Web Application Firewall (CloudFlare) 
[!] Testing parameter: search 
[!] Reflections found: 6 
[~] Analysing reflections 
[~] Generating payloads 
[!] Payloads generated: 3120 
```
I think the issue is in response.
Some web apps still throws this error even without `--proxy`

**Comment by Hugo-Lua** [comment]
might be xss protection

**Comment by AdithyakrishnaV** [comment]
The solution is, XSStrike  work  with Python 3.8 or 3.9.
Consider creating a virtual environment with an older Python version:
pyenv install 3.8.10
pyenv virtualenv 3.8.10 xsstrike-env
pyenv activate xsstrike-env

After this you may run into an error: ModuleNotFoundError: No module named 'requests'
Just run this command: 
pip install requests

Now the tool will be working just fine.
If it helped consider subscribing to my YouTube channel: https://www.youtube.com/channel/UCR9txckubHGilBvNGvud_dg
I create contents about bug boundy and reverse engineering.

**Comment by ac0z** [comment]
![image](https://github.com/user-attachments/assets/e5e2244c-a386-40ba-8371-b905a78571b9)

using python 3.9. Can you help me?

**Comment by gauravlinux** [comment]
still this tool is not working

**Comment by AdithyakrishnaV** [comment]
> ![image](https://private-user-images.githubusercontent.com/167352447/363427433-e5e2244c-a386-40ba-8371-b905a78571b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTM1NzksIm5iZiI6MTcyNjgxMzI3OSwicGF0aCI6Ii8xNjczNTI0NDcvMzYzNDI3NDMzLWU1ZTIyNDRjLWEzODYtNDBiYS04MzcxLWI5MDVhNzg1NzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNjIxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTI2NzExNDIxZDIxMGFlNmQ2MDZmM2MxMTA4MjFjNDYzMTFmZDgwYTQ5YmMxMWFiNzI3MmViZjY3MDM3MzNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lR6_kUhiEGkb82sOC4-MeVJ2L--drIXty5AklEqodNE)
> 
> using python 3.9. Can you help me?

try with 3.8.10

**Comment by ianwolf99** [comment]
not working

**Comment by ragawarsh** [comment]
**step1.**
 sudo apt update

**step2.** 
sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git

**step3.** 
curl https://pyenv.run | bash

**step4.** 
nano ~/.bashrc

**step5.** 
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

**step6.** 
source ~/.bashrc

**step7.** 
nano ~/.zshrc

**step8.** 
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
 step9. source ~/.zshrc

**check version by** 
pyenv --version


**Then follow these commands**(move the directory in which XSStrike is installed)
pyenv install 3.8.10
pyenv virtualenv 3.8.10 xsstrike-env
pyenv activate xsstrike-env

**Comment by s0md3v** [comment]
This issue has been fixed in the latest patch.
