### ISSUE TITLE
Error occurs windows  10

### ISSUE THREAD

**Issue by halith-smh** [s0md3v/XSStrike#379]
Traceback (most recent call last):
  File "D:\XSStrike-master\XSStrike-master\xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "D:\XSStrike-master\XSStrike-master\modes\scan.py", line 81, in scan
    vectors = generator(occurences, response.text)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\XSStrike-master\XSStrike-master\core\generator.py", line 136, in generator
    closer = jsContexter(script)
             ^^^^^^^^^^^^^^^^^^^
  File "D:\XSStrike-master\XSStrike-master\core\jsContexter.py", line 11, in jsContexter
    pre = re.sub(r'(?s)\{.*?\}|(?s)\(.*?\)|(?s)".*?"|(?s)\'.*?\'', '', pre)

**Comment by s0md3v** [comment]
This error has been fixed in the latest release.
