### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'uzzer'

### ISSUE THREAD

**Issue by Troyber** [s0md3v/XSStrike#388]
C:\Users\86188\Desktop\tool\XSStrike-master>python xsstrike.py -u "http://localhost/1.php?x=1" -fuzzer

        XSStrike v3.1.5

Traceback (most recent call last):
  File "xsstrike.py", line 149, in <module>
    payloadList = list(filter(None, reader(args_file)))
  File "C:\Users\86188\Desktop\tool\XSStrike-master\core\utils.py", line 204, in reader
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'uzzer'

May I ask why this error occurred and how to fix it

**Comment by Troyber** [comment]
C:\Users\86188\Desktop\tool\XSStrike-master>python xsstrike.py -u "http://localhost/1.php?x=1" --fuzzer
