### ISSUE TITLE
Unable to connect to the target (Not Solved)

### ISSUE THREAD

**Issue by Ahmed222234** [s0md3v/XSStrike#398]
when I try this command:
python3 xsstrike.py -u "http://94.237.58.148:56322/index.php?parameter=test";

I got this error:
[!!] Unable to connect to the target. 
[~] Checking for DOM vulnerabilities 
[!!] Unable to connect to the target. 
Traceback (most recent call last):
  File "/home/user/XSStrike/xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "/home/user/XSStrike/modes/scan.py", line 52, in scan
    WAF = wafDetector(
          ^^^^^^^^^^^^
  File "/home/user/XSStrike/core/wafDetector.py", line 25, in wafDetector
    if int(code) >= 400:
       ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'

how to solve this issue?

**Comment by darkb0ts** [comment]
check website is working properly using httpie or httpx ,any other tool. It appears to be working well for me

**Comment by Ahmed222234** [comment]
@darkb0ts it works on httpie, the link is generated with htb academy
how to make it work?
