### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by FazanLone** [s0md3v/XSStrike#403]
C:\Users\hp\Downloads\XSStrike-master>xsstrike.py

        XSStrike v3.1.5

Traceback (most recent call last):
  File "C:\Users\hp\Downloads\XSStrike-master\xsstrike.py", line 117, in <module>
    from core.photon import photon
  File "C:\Users\hp\Downloads\XSStrike-master\core\photon.py", line 8, in <module>
    from core.requester import requester
  File "C:\Users\hp\Downloads\XSStrike-master\core\requester.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by darkb0ts** [comment]
Bro Please mention Your Python Version and  `pip install requests` or `pip3 install requests `
