### ISSUE TITLE
doses not working solve this issue

### ISSUE THREAD

**Issue by shetty197** [s0md3v/XSStrike#410]
File "/home/kali/XSStrike/xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "/home/kali/XSStrike/modes/scan.py", line 81, in scan
    vectors = generator(occurences, response.text)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/XSStrike/core/generator.py", line 136, in generator
    closer = jsContexter(script)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/XSStrike/core/jsContexter.py", line 11, in jsContexter
    pre = re.sub(r'(?s)\{.*?\}|(?s)\(.*?\)|(?s)".*?"|(?s)\'.*?\'', '', pre)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '

**Comment by Anub1s1999** [comment]
got the same error: 
        XSStrike v3.1.5                                                                                                       
                                                                                                                              
[~] Checking for DOM vulnerabilities 
[+] WAF Status: Offline 
[!] Testing parameter: search 
[!] Reflections found: 11 
[~] Analysing reflections 
[~] Generating payloads 
Traceback (most recent call last):
  File "/home/kali/XSStrike/xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "/home/kali/XSStrike/modes/scan.py", line 81, in scan
    vectors = generator(occurences, response.text)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/XSStrike/core/generator.py", line 136, in generator
    closer = jsContexter(script)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/XSStrike/core/jsContexter.py", line 11, in jsContexter
    pre = re.sub(r'(?s)\{.*?\}|(?s)\(.*?\)|(?s)".*?"|(?s)\'.*?\'', '', pre)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 12

Python3 version: 
python 3.11.8

Pip3 version: 
pip 24.2 from /usr/local/lib/python3.11/dist-packages/pip (python 3.11)

**Comment by kuldeep143s** [comment]
also facing this error 



------------------------------------------------------------
[+] WAF Status: Offline
[!] Testing parameter: keywords
[!] Reflections found: 5
[~] Analysing reflections
[~] Generating payloads
Traceback (most recent call last):
  File "/home/kaal/XSStrike/xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "/home/kaal/XSStrike/modes/scan.py", line 81, in scan
    vectors = generator(occurences, response.text)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kaal/XSStrike/core/generator.py", line 136, in generator
    closer = jsContexter(script)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/kaal/XSStrike/core/jsContexter.py", line 11, in jsContexter
    pre = re.sub(r'(?s)\{.*?\}|(?s)\(.*?\)|(?s)".*?"|(?s)\'.*?\'', '', pre)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '

**Comment by s0md3v** [comment]
This issue has been fixed in the latest patch.
