### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by arcel1945** [s0md3v/XSStrike#416]
error:
python xsstrike.py -u http://www.johnpaulschool.sch.id/?p=FUZZ

        XSStrike v3.1.5

[!!] Unable to connect to the target.
[~] Checking for DOM vulnerabilities
[!!] Unable to connect to the target.
Traceback (most recent call last):
  File "/root/XSStrike/xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "/root/XSStrike/modes/scan.py", line 52, in scan
    WAF = wafDetector(
          ^^^^^^^^^^^^
  File "/root/XSStrike/core/wafDetector.py", line 25, in wafDetector
    if int(code) >= 400:
       ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'

![image](https://github.com/user-attachments/assets/24743265-03a4-4a32-b0bc-cbd2b2bef4b1)

**Comment by yzyz888** [comment]
getting the same issue
