### ISSUE TITLE
Anyone can fix this 

### ISSUE THREAD

**Issue by kravchenko21456** [s0md3v/XSStrike#62]
Traceback (most recent call last):
  File "xsstrike", line 21, in <module>
    from core.injector import inject
  File "/root/XSStrike/core/injector.py", line 9, in <module>
    from core.test_param_check import test_param_check
  File "/root/XSStrike/core/test_param_check.py", line 4, in <module>
    from fuzzywuzzy import fuzz # Module for fuzzy matching
ModuleNotFoundError: No module named 'fuzzywuzzy'

**Comment by s0md3v** [comment]
Please check previously closed issues for solution.
