### ISSUE TITLE
requirements.txt missing photon

### ISSUE THREAD

**Issue by Hipapheralkus** [s0md3v/XSStrike#70]
```
Traceback (most recent call last):
  File "./xsstrike.py", line 30, in <module>
    from core.photon import photon
  File "/opt/XSStrike/core/photon.py", line 2, in <module>
    import tld
ModuleNotFoundError: No module named 'tld'
```

after running pip3 install photon everything works

**Comment by s0md3v** [comment]
A custom build of Photon has been included in XSStrike, you don't need to install it with `pip`.
Thanks for reporting,  I added `tld` to `requirements.txt`
