### ISSUE TITLE
free variable 'threadpool' referenced before assignment

### ISSUE THREAD

**Issue by DeWolfRobin** [s0md3v/XSStrike#77]
Hi, I got this error while running
`Traceback (most recent call last):
  File "xsstrike.py", line 232, in <module>
    singleTarget(target, paramData)
  File "xsstrike.py", line 113, in singleTarget
    params = arjun(url, GET, headers, delay)
  File "/root/XSStrike/core/arjun.py", line 29, in arjun
    for i, _ in enumerate(concurrent.futures.as_completed(futures)):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 217, in as_completed
    fs = set(fs)
  File "/root/XSStrike/core/arjun.py", line 28, in <genexpr>
    futures = (threadpool.submit(checky, param, paraNames, url, headers, GET, delay) for param in blindParams)
NameError: free variable 'threadpool' referenced before assignment in enclosing scope
`

**Comment by DeWolfRobin** [comment]
python3 xsstrike.py -u telenet.be --params
was the command,
4.18.0-kali2-amd64
is my os

**Comment by s0md3v** [comment]
[Fixed]
