### ISSUE TITLE
checking for dom xss this happens

### ISSUE THREAD

**Issue by soupnatzi** [s0md3v/XSStrike#81]
Traceback (most recent call last):
  File "/root/XSS/XSStrike/core/generator.py", line 66, in generator
    script = scripts[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xsstrike.py", line 237, in <module>
    singleTarget(target, paramData)
  File "xsstrike.py", line 146, in singleTarget
    vectors = generator(occurences, response)
  File "/root/XSS/XSStrike/core/generator.py", line 68, in generator
    script = scripts[0]
IndexError: list index out of range

**Comment by soupnatzi** [comment]
this is seperate where do i go to add more payloads to test

**Comment by s0md3v** [comment]
XSStrike doesn't have a payload list, it generates payloads on it's own based on target's response.

**Comment by soupnatzi** [comment]
thanks for the quick response see i have this dom xss which looks vulnerable but some reason no xss is showing here is the example 
document.write(""+dayarray[day]+", "+montharray[month]+" "+daym+", "+year+"")
